name: ftauth
description: Client-side library for the FTAuth server.
version: 1.0.0-nullsafety.0
homepage: https://github.com/ftauth/ftauth

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  json_annotation: ^4.0.0-nullsafety.0
  equatable: ^2.0.0-nullsafety.0
  http: ^0.12.2
  hive: ^1.4.4+1
  oauth2: ^1.6.3
  jose: ^0.2.1+1

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.0
  test: ^1.16.0-nullsafety.0
  build_runner: ^1.10.0
  json_serializable: ^4.0.0-nullsafety.0
