name: ftauth
description: A starting point for Dart libraries or applications.
version: 1.0.0-nullsafety.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  json_annotation: ^4.0.0-nullsafety.0
  equatable: ^2.0.0-nullsafety.0
  http: ^0.12.2
  oauth2: ^1.6.3
  jose: ^0.2.1+1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  build_runner: ^1.10.0
  json_serializable: ^4.0.0-nullsafety.0
