name: ftauth
description: Client-side library for the FTAuth server.
version: 1.0.0-nullsafety.0
homepage: https://github.com/ftauth/sdk-dart

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  json_annotation: ^4.0.0-nullsafety.0
  equatable: ^2.0.0-nullsafety.0
  hive: ^1.4.4+1
  oauth2:
    git:
      url: https://github.com/dnys1/oauth2.git
      ref: nullsafety
  jose: ^0.2.1+1
  crypto_keys: ^0.1.3
  uuid: ^2.2.2
  webcrypto:
    git:
      url: https://github.com/ftauth/webcrypto.dart
      ref: master
      path: webcrypto

dependency_overrides:
  http:
    git:
      url: https://github.com/dart-lang/http.git
      ref: stronger-types
  http_parser: ^4.0.0-nullsafety
  crypto: ^3.0.0-nullsafety.0

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.0
  test: ^1.16.0-nullsafety.0
  build_runner: ^1.10.0
  json_serializable: ^4.0.0-nullsafety.0
  mockito: ^5.0.0-nullsafety.1
