name: ftauth
description: Client-side library for the FTAuth server.
version: 0.1.0
homepage: https://github.com/ftauth/sdk-dart
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto: ^3.0.0
  equatable: ^2.0.0
  hive: ^2.0.0
  ftauth_jwt:
    path: ../ftauth_jwt
  js: ^0.6.3
  json_annotation: ^4.3.0
  oauth2: ^2.0.0
  pointycastle: ^3.0.0
  uuid: ^3.0.0

# dependency_overrides:
#   ftauth_jwt:
#     path: ../ftauth_jwt

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.0.1
  mockito: ^5.0.0
  lints: ^1.0.0
  test: ^1.16.0