name: ftauth_storage_platform_interface
description: Platform interface for FTAuth secure storage adapter.
version: 0.1.0
homepage: https://github.com/ftauth/sdk-dart

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ftauth: ^0.1.0
  meta: ^1.3.0
  plugin_platform_interface: ^2.0.1
  shared_preferences: ^2.0.9

dependency_overrides:
  ftauth:
    path: ../../ftauth
  ftauth_jwt:
    path: ../../ftauth_jwt

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  pigeon: ^1.0.0
