name: ftauth_storage_platform_interface
description: A new Flutter package project.
version: 0.1.0
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  ftauth: ^0.1.0
  ftauth_flutter_platform_interface: ^0.1.0
  plugin_platform_interface: ^2.0.0
  shared_preferences: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
