name: ftauth_example
description: Demonstrates how to use the sso_module plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ftauth_flutter:
    path: ../ftauth_flutter/ftauth_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.16.0
  webdriver: ^3.0.0

flutter:
  uses-material-design: true