name: angulardart
description: FTAuth example with AngularDart
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.15.0-0 <3.0.0'

dependencies:
  amplify_appsync:
    path: third_party/amplify_appsync
  amplify_common:
    path: third_party/amplify_common
  angular: ^7.0.0
  angular_router: ^3.0.1
  ftauth: ^0.1.1
  json_annotation: '>=4.4.0 <4.5.0'

dev_dependencies:
  build_runner: ^2.1.5
  build_web_compilers: ^3.2.1
  json_serializable: ^6.1.0
  lints: ^1.0.0
  sass_builder: ^2.1.4
