name: ftauth_flutter
description: FTAuth bindings and widget library for Flutter.
version: 0.1.0
homepage: https://github.com/ftauth/sdk-dart

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  ftauth: ^0.2.0
  ftauth_flutter_platform_interface: ^0.1.0
  ftauth_flutter_android: ^0.1.0
  ftauth_flutter_ios: ^0.1.0
  ftauth_flutter_web: ^0.1.0
  ftauth_flutter_macos: ^0.1.0
  ftauth_flutter_windows: ^0.1.0
  ftauth_flutter_linux: ^0.1.0
  ftauth_storage: ^0.1.0
  shared_preferences: ^2.0.0
  webview_flutter: ^2.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        default_package: ftauth_flutter_android
      ios:
        default_package: ftauth_flutter_ios
      web:
        default_package: ftauth_flutter_web
      macos:
        default_package: ftauth_flutter_macos
      windows:
        default_package: ftauth_flutter_windows
      linux:
        default_package: ftauth_flutter_linux
