// Autogenerated from Pigeon (v1.0.12), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class FTAuthClientConfiguration;

@interface FTAuthClientConfiguration : NSObject
@property(nonatomic, copy, nullable) NSString * authorizationEndpoint;
@property(nonatomic, copy, nullable) NSString * tokenEndpoint;
@property(nonatomic, copy, nullable) NSString * clientId;
@property(nonatomic, copy, nullable) NSString * clientSecret;
@property(nonatomic, copy, nullable) NSString * redirectUri;
@property(nonatomic, strong, nullable) NSArray<NSString *> * scopes;
@property(nonatomic, copy, nullable) NSString * state;
@property(nonatomic, copy, nullable) NSString * codeVerifier;
@end

/// The codec used by FTAuthNativeLogin.
NSObject<FlutterMessageCodec> *FTAuthNativeLoginGetCodec(void);

@protocol FTAuthNativeLogin
- (void)loginConfig:(nullable FTAuthClientConfiguration *)config completion:(void(^)(NSDictionary<NSString *, NSString *> *_Nullable, FlutterError *_Nullable))completion;
@end

extern void FTAuthNativeLoginSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FTAuthNativeLogin> *_Nullable api);

NS_ASSUME_NONNULL_END
