name: ftauth_storage
description: Secure storage adapter for FTAuth.
version: 0.1.0
homepage: https://github.com/ftauth/sdk-dart

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  ftauth: ^0.1.0
  ftauth_storage_platform_interface: ^0.1.0
  ftauth_storage_android: ^0.1.0
  ftauth_storage_ios: ^0.1.0
  ftauth_storage_web: ^0.1.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        default_package: ftauth_storage_android
      ios:
        default_package: ftauth_storage_ios
      web:
        default_package: ftauth_storage_web
