name: ftauth_storage
description: A new flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.example.ftauth_storage
        pluginClass: FtauthStoragePlugin
      ios:
        pluginClass: FtauthStoragePlugin
      web:
        default_package: ftauth_storage_web

dependencies:
  flutter:
    sdk: flutter
  ftauth:
    path: ../../ftauth
  ftauth_storage_platform_interface:
    path: ../ftauth_storage_platform_interface
  ftauth_storage_web:
    path: ../ftauth_storage_web

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

