name: ftauth_storage
description: A new flutter plugin project.
version: 0.1.0
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: io.ftauth.ftauth_storage
        pluginClass: FtauthStoragePlugin
      ios:
        pluginClass: FtauthStoragePlugin
      web:
        default_package: ftauth_storage_web

dependencies:
  flutter:
    sdk: flutter
  ftauth: ^0.1.0
  ftauth_storage_platform_interface: ^0.1.0
  ftauth_storage_web: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

