name: ftauth_flutter_windows
description: FTAuth bindings for Windows.
version: 0.1.0
homepage: https://github.com/ftauth/sdk-dart

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: FTAuthFlutterPlugin

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
