name: ftauth_flutter_windows
description: FTAuth bindings for Windows.
version: 0.1.0
homepage: https://github.com/ftauth/sdk-dart

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  ftauth_flutter_platform_interface: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  url_launcher: ^6.0.0

dependency_overrides:
  ftauth_flutter_platform_interface:
    path: ../ftauth_flutter_platform_interface
  ftauth:
    path: ../../ftauth
  ftauth_jwt:
    path: ../../ftauth_jwt

flutter:
  plugin:
    implements: ftauth_flutter
    platforms:
      windows:
        dartPluginClass: FTAuthFlutterWindows
