name: ftauth_flutter_platform_interface
description: FTAuth Flutter platform interface.
version: 0.1.0
homepage: https://github.com/ftauth/sdk-dart

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ftauth: ^0.1.0
  meta: ^1.3.0
  plugin_platform_interface: ^2.0.1
  url_launcher: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
