name: ftauth_flutter
description: FTAuth bindings and widget library for Flutter.
version: 0.1.0
homepage: https://github.com/ftauth/sdk-dart

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  ftauth:
    path: ../ftauth

  hive_flutter: ^0.3.1
  url_launcher: ^5.7.2
  uni_links: ^0.4.0
  flutter_secure_storage: ^3.3.5

dependency_overrides:
  http:
    git:
      url: https://github.com/dart-lang/http.git
      ref: stronger-types
  http_parser: ^4.0.0-nullsafety
  crypto: ^3.0.0-nullsafety.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
