name: ftauth_flutter
description: FTAuth bindings and widget library for Flutter.
version: 0.1.0
homepage: https://github.com/ftauth/sdk-dart

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  ftauth:
    path: ../ftauth
  url_launcher: ^6.0.0-nullsafety.1
  uni_links: ^0.4.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
