name: ftauth_storage_web
description: A new flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    implements: ftauth_storage
    platforms:
      web:
        pluginClass: FTAuthStorageWeb
        fileName: ftauth_storage_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  ftauth_storage_platform_interface:
    path: ../ftauth_storage_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
