name: ftauth_storage_web
description: Web bindings for FTAuth secure storage adapter.
version: 0.1.0
homepage: https://github.com/ftauth/sdk-dart

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  ftauth_storage_platform_interface: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FTAuthStorageWeb
        fileName: ftauth_storage_web.dart
