name: ftauth_flutter_web
description: FTAuth bindings for Flutter Web.
version: 0.1.0
homepage: https://github.com/ftauth/sdk-dart

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FTAuthFlutterWeb
        fileName: ftauth_flutter_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  ftauth_flutter_platform_interface: ^0.1.0
  ftauth: ^0.1.0
  http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
