# Created with package:mono_repo v5.0.4
name: Dart Lint
on:
  push:
    branches:
      - main
      - master
  pull_request:
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github

jobs:
  job_001:
    name: mono_repo self validate
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.6
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:stable"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v2.3.5
      - name: mono_repo self validate
        run: dart pub global activate mono_repo 5.0.4
      - name: mono_repo self validate
        run: dart pub global run mono_repo generate --validate
  job_002:
    name: "analyze_and_format; Dart 2.14.0; PKGS: ftauth, ftauth_jwt; `dart format --output=none --set-exit-if-changed .`, `dart analyze --fatal-infos .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.6
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:2.14.0;packages:ftauth-ftauth_jwt;commands:format-analyze"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:2.14.0;packages:ftauth-ftauth_jwt
            os:ubuntu-latest;pub-cache-hosted;dart:2.14.0
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: "2.14.0"
      - id: checkout
        uses: actions/checkout@v2.3.5
      - id: ftauth_pub_upgrade
        name: ftauth; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: ftauth
        run: dart pub upgrade
      - name: "ftauth; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.ftauth_pub_upgrade.conclusion == 'success'"
        working-directory: ftauth
        run: "dart format --output=none --set-exit-if-changed ."
      - name: "ftauth; dart analyze --fatal-infos ."
        if: "always() && steps.ftauth_pub_upgrade.conclusion == 'success'"
        working-directory: ftauth
        run: dart analyze --fatal-infos .
      - id: ftauth_jwt_pub_upgrade
        name: ftauth_jwt; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: ftauth_jwt
        run: dart pub upgrade
      - name: "ftauth_jwt; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.ftauth_jwt_pub_upgrade.conclusion == 'success'"
        working-directory: ftauth_jwt
        run: "dart format --output=none --set-exit-if-changed ."
      - name: "ftauth_jwt; dart analyze --fatal-infos ."
        if: "always() && steps.ftauth_jwt_pub_upgrade.conclusion == 'success'"
        working-directory: ftauth_jwt
        run: dart analyze --fatal-infos .
  job_003:
    name: "analyze_and_format; Dart dev; PKGS: ftauth, ftauth_jwt; `dart format --output=none --set-exit-if-changed .`, `dart analyze --fatal-infos .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.6
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:ftauth-ftauth_jwt;commands:format-analyze"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:ftauth-ftauth_jwt
            os:ubuntu-latest;pub-cache-hosted;dart:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: dev
      - id: checkout
        uses: actions/checkout@v2.3.5
      - id: ftauth_pub_upgrade
        name: ftauth; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: ftauth
        run: dart pub upgrade
      - name: "ftauth; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.ftauth_pub_upgrade.conclusion == 'success'"
        working-directory: ftauth
        run: "dart format --output=none --set-exit-if-changed ."
      - name: "ftauth; dart analyze --fatal-infos ."
        if: "always() && steps.ftauth_pub_upgrade.conclusion == 'success'"
        working-directory: ftauth
        run: dart analyze --fatal-infos .
      - id: ftauth_jwt_pub_upgrade
        name: ftauth_jwt; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: ftauth_jwt
        run: dart pub upgrade
      - name: "ftauth_jwt; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.ftauth_jwt_pub_upgrade.conclusion == 'success'"
        working-directory: ftauth_jwt
        run: "dart format --output=none --set-exit-if-changed ."
      - name: "ftauth_jwt; dart analyze --fatal-infos ."
        if: "always() && steps.ftauth_jwt_pub_upgrade.conclusion == 'success'"
        working-directory: ftauth_jwt
        run: dart analyze --fatal-infos .
