# Created with package:mono_repo v6.0.0
name: Test
on:
  push:
    branches:
      - main
      - master
  pull_request:
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github

jobs:
  job_001:
    name: "unit_test; Flutter beta; PKGS: ftauth_flutter/ftauth_flutter_platform_interface, ftauth_storage/ftauth_storage_platform_interface; `flutter test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.7
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:beta;packages:ftauth_flutter/ftauth_flutter_platform_interface-ftauth_storage/ftauth_storage_platform_interface;commands:test_2"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:beta;packages:ftauth_flutter/ftauth_flutter_platform_interface-ftauth_storage/ftauth_storage_platform_interface
            os:ubuntu-latest;pub-cache-hosted;sdk:beta
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: subosito/flutter-action@v1.5.3
        with:
          channel: beta
      - id: checkout
        uses: actions/checkout@v2.4.0
      - id: ftauth_flutter_ftauth_flutter_platform_interface_pub_upgrade
        name: ftauth_flutter/ftauth_flutter_platform_interface; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: ftauth_flutter/ftauth_flutter_platform_interface
        run: dart pub upgrade
      - name: ftauth_flutter/ftauth_flutter_platform_interface; flutter test
        if: "always() && steps.ftauth_flutter_ftauth_flutter_platform_interface_pub_upgrade.conclusion == 'success'"
        working-directory: ftauth_flutter/ftauth_flutter_platform_interface
        run: flutter test
      - id: ftauth_storage_ftauth_storage_platform_interface_pub_upgrade
        name: ftauth_storage/ftauth_storage_platform_interface; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: ftauth_storage/ftauth_storage_platform_interface
        run: dart pub upgrade
      - name: ftauth_storage/ftauth_storage_platform_interface; flutter test
        if: "always() && steps.ftauth_storage_ftauth_storage_platform_interface_pub_upgrade.conclusion == 'success'"
        working-directory: ftauth_storage/ftauth_storage_platform_interface
        run: flutter test
  job_002:
    name: "unit_test; Dart dev; PKGS: ftauth, ftauth_jwt; `dart test --coverage=coverage`, `dart test -p chrome --coverage=coverage`, `../tool/coverage.sh`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.7
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:ftauth-ftauth_jwt;commands:test_0-test_1-command"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:ftauth-ftauth_jwt
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: dev
      - id: checkout
        uses: actions/checkout@v2.4.0
      - id: ftauth_pub_upgrade
        name: ftauth; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: ftauth
        run: dart pub upgrade
      - name: "ftauth; dart test --coverage=coverage"
        if: "always() && steps.ftauth_pub_upgrade.conclusion == 'success'"
        working-directory: ftauth
        run: "dart test --coverage=coverage"
      - name: "ftauth; dart test -p chrome --coverage=coverage"
        if: "always() && steps.ftauth_pub_upgrade.conclusion == 'success'"
        working-directory: ftauth
        run: "dart test -p chrome --coverage=coverage"
      - name: ftauth; ../tool/coverage.sh
        if: "always() && steps.ftauth_pub_upgrade.conclusion == 'success'"
        working-directory: ftauth
        run: ../tool/coverage.sh
      - id: ftauth_jwt_pub_upgrade
        name: ftauth_jwt; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: ftauth_jwt
        run: dart pub upgrade
      - name: "ftauth_jwt; dart test --coverage=coverage"
        if: "always() && steps.ftauth_jwt_pub_upgrade.conclusion == 'success'"
        working-directory: ftauth_jwt
        run: "dart test --coverage=coverage"
      - name: "ftauth_jwt; dart test -p chrome --coverage=coverage"
        if: "always() && steps.ftauth_jwt_pub_upgrade.conclusion == 'success'"
        working-directory: ftauth_jwt
        run: "dart test -p chrome --coverage=coverage"
      - name: ftauth_jwt; ../tool/coverage.sh
        if: "always() && steps.ftauth_jwt_pub_upgrade.conclusion == 'success'"
        working-directory: ftauth_jwt
        run: ../tool/coverage.sh
  job_003:
    name: "unit_test; Dart stable; PKGS: ftauth, ftauth_jwt; `dart test --coverage=coverage`, `dart test -p chrome --coverage=coverage`, `../tool/coverage.sh`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.7
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:ftauth-ftauth_jwt;commands:test_0-test_1-command"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:ftauth-ftauth_jwt
            os:ubuntu-latest;pub-cache-hosted;sdk:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v2.4.0
      - id: ftauth_pub_upgrade
        name: ftauth; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: ftauth
        run: dart pub upgrade
      - name: "ftauth; dart test --coverage=coverage"
        if: "always() && steps.ftauth_pub_upgrade.conclusion == 'success'"
        working-directory: ftauth
        run: "dart test --coverage=coverage"
      - name: "ftauth; dart test -p chrome --coverage=coverage"
        if: "always() && steps.ftauth_pub_upgrade.conclusion == 'success'"
        working-directory: ftauth
        run: "dart test -p chrome --coverage=coverage"
      - name: ftauth; ../tool/coverage.sh
        if: "always() && steps.ftauth_pub_upgrade.conclusion == 'success'"
        working-directory: ftauth
        run: ../tool/coverage.sh
      - id: ftauth_jwt_pub_upgrade
        name: ftauth_jwt; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: ftauth_jwt
        run: dart pub upgrade
      - name: "ftauth_jwt; dart test --coverage=coverage"
        if: "always() && steps.ftauth_jwt_pub_upgrade.conclusion == 'success'"
        working-directory: ftauth_jwt
        run: "dart test --coverage=coverage"
      - name: "ftauth_jwt; dart test -p chrome --coverage=coverage"
        if: "always() && steps.ftauth_jwt_pub_upgrade.conclusion == 'success'"
        working-directory: ftauth_jwt
        run: "dart test -p chrome --coverage=coverage"
      - name: ftauth_jwt; ../tool/coverage.sh
        if: "always() && steps.ftauth_jwt_pub_upgrade.conclusion == 'success'"
        working-directory: ftauth_jwt
        run: ../tool/coverage.sh
  job_004:
    name: "unit_test; Flutter stable; PKGS: ftauth_flutter/ftauth_flutter_platform_interface, ftauth_storage/ftauth_storage_platform_interface; `flutter test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.7
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:ftauth_flutter/ftauth_flutter_platform_interface-ftauth_storage/ftauth_storage_platform_interface;commands:test_2"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:ftauth_flutter/ftauth_flutter_platform_interface-ftauth_storage/ftauth_storage_platform_interface
            os:ubuntu-latest;pub-cache-hosted;sdk:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: subosito/flutter-action@v1.5.3
        with:
          channel: stable
      - id: checkout
        uses: actions/checkout@v2.4.0
      - id: ftauth_flutter_ftauth_flutter_platform_interface_pub_upgrade
        name: ftauth_flutter/ftauth_flutter_platform_interface; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: ftauth_flutter/ftauth_flutter_platform_interface
        run: dart pub upgrade
      - name: ftauth_flutter/ftauth_flutter_platform_interface; flutter test
        if: "always() && steps.ftauth_flutter_ftauth_flutter_platform_interface_pub_upgrade.conclusion == 'success'"
        working-directory: ftauth_flutter/ftauth_flutter_platform_interface
        run: flutter test
      - id: ftauth_storage_ftauth_storage_platform_interface_pub_upgrade
        name: ftauth_storage/ftauth_storage_platform_interface; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: ftauth_storage/ftauth_storage_platform_interface
        run: dart pub upgrade
      - name: ftauth_storage/ftauth_storage_platform_interface; flutter test
        if: "always() && steps.ftauth_storage_ftauth_storage_platform_interface_pub_upgrade.conclusion == 'success'"
        working-directory: ftauth_storage/ftauth_storage_platform_interface
        run: flutter test
