name: Run Tests

# Run this everytime a new commit is pushed to the repo
on: push

jobs:
  dart-test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: dev

      - run: bash scripts/test.sh
        working-directory: ftauth
